--Drop the table because WRITE_TRUNCATE replaces the table and interfers with the table's schema as defined here
DROP TABLE IF EXISTS brewData.staging_beverages;

CREATE OR REPLACE TABLE brewData.staging_beverages 
(
    id STRING NOT NULL OPTIONS(description="The primary key for the table"),
    name STRING OPTIONS(description="The name of the beverage"),
    beverage_type STRING OPTIONS(description="The type of beverage"),
    brewery_id STRING NOT NULL OPTIONS(description="The ID for the corresponding brewery"),
    is_active BOOL OPTIONS(description="Indicates if the beverage is stll active"),
    updated_at DATETIME OPTIONS(description="The timestamp this record was updated by my Python script"),
    created_at DATETIME OPTIONS(description="The timestamp this record was generated by my Python script"),
);