
version: 2

models:
    - name: dimBreweries
      description: "A list of breweries and some information about them"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: name
            description: "The name of the brewery"
          - name: brewery_type
            description: "The type of brewery"
          - name: street
            description: "The street address for the brewery"
          - name: address_2
            description: "The 2nd address line for the brewery"
          - name: address_3
            description: "The 3rd address line for the brewery"
          - name: city
            description: "The city of the brewery"
          - name: state
            description: "The state the brewery is located in"
          - name: county_province
            description: "The county or province the brewery is located in"
          - name: postal_code
            description: "The postal code of the brewery"
          - name: country
            description: "The country of the brewery"
          - name: longitude
            description: "The longitude of the brewery's location"
          - name: latitude
            description: "The latitude of the brewery's location"
          - name: phone_num
            description: "The phone number of the brewery"
          - name: website_url
            description: "The URL of the website for the brewery"